name: connect-publish
on:
  push:
    branches: [master, main]

jobs:
  test-r: 
    name: test-r
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '3.5.3' # The R version to download (if necessary) and use.
      - run: Rscript -e 'print("hello")'

  test-app:
    name: test-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.0
          use-public-rspm: true
      - name: Remove `.Rprofile`
        shell: bash
        run: |
          rm .Rprofile
      - uses: r-lib/actions/setup-renv@v2 # use our renv.lock
      - name: Test Shiny App
        shell: Rscript {0}
        run: |
          shinytest2::test_app()

  connect-publish:
    name: connect-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: acl
          dir: |
            .:/learn_shinytest2

  test-then-connect-publish:
    name: test-then-connect-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.0
          use-public-rspm: true
      - name: Remove `.Rprofile`
        shell: bash
        run: |
          rm .Rprofile
      - uses: r-lib/actions/setup-renv@v2 # use our renv.lock
      - name: Test Shiny App
        shell: Rscript {0}
        run: |
          shinytest2::test_app()    
      - name: Create manifest.json
        shell: Rscript {0}
        run: |
          rsconnect::writeManifest()
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: acl
          dir: |
            .:/learn_shinytest2